In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv("./DataSets/house_price_classification.csv")

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

display(train_data.head())

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,2
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,1
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,2
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,1
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,2

In [4]:
train_data["CentralAir"].unique()

array(['Y', 'N'], dtype=object)

In [5]:
train_data.shape

(1460, 83)

In [6]:
len(train_data.columns)

83

In [7]:
#values in train data set
train_cols = train_data.columns
missing_train_cols = []
missing_train_value = []
for col in train_cols:
    if train_data[col].isnull().any():
        missing_train_cols.append(col)
        missing_train_value.append(train_data[col].isnull().sum())
        print(f"column {col} have {train_data[col].isnull().sum()} missing values")
        #print(missing_train_cols,missing_train_val)

column LotFrontage have 259 missing values
column Alley have 1369 missing values
column MasVnrType have 872 missing values
column MasVnrArea have 8 missing values
column BsmtQual have 37 missing values
column BsmtCond have 37 missing values
column BsmtExposure have 38 missing values
column BsmtFinType1 have 37 missing values
column BsmtFinType2 have 38 missing values
column Electrical have 1 missing values
column FireplaceQu have 690 missing values
column GarageType have 81 missing values
column GarageYrBlt have 81 missing values
column GarageFinish have 81 missing values
column GarageQual have 81 missing values
column GarageCond have 81 missing values
column PoolQC have 1453 missing values
column Fence have 1179 missing values
column MiscFeature have 1406 missing values

In [8]:
# columns = train_data.columns
# isNull_col = []
# isNull_val = []
# for null_cols in columns:
#   if train_data[null_cols].isnull().sum() > 0:
#     isNull_col.append(null_cols)
#     isNull_val.append(train_data[null_cols].isnull().sum())
# print(isNull_col)

In [9]:
train_data.drop(["SalePrice","PriceCategory"],axis=1 )

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
1456,1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal
1457,1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Gd,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal
1458,1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,NaN,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
1459,1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal

In [10]:
train_data.drop(["PoolQC","MiscFeature"], axis = 1)

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,0,2,2008,WD,Normal,208500,2
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,0,5,2007,WD,Normal,181500,1
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,0,9,2008,WD,Normal,223500,2
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,0,2,2006,WD,Abnorml,140000,1
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,0,12,2008,WD,Normal,250000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,NaN,0,8,2007,WD,Normal,175000,1
1456,1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,MnPrv,0,2,2010,WD,Normal,210000,2
1457,1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Gd,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,GdPrv,2500,5,2010,WD,Normal,266500,2
1458,1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,NaN,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,NaN,0,4,2010,WD,Normal,142125,1
1459,1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,0,6,2008,WD,Normal,147500,1

In [11]:
train_data["LotFrontage"] = train_data["LotFrontage"].fillna(train_data["LotFrontage"].median())
train_data["MasVnrArea"] = train_data["MasVnrArea"].fillna(train_data["MasVnrArea"].median())
train_data["GarageYrBlt"] = train_data["GarageYrBlt"].fillna(train_data["GarageYrBlt"].median())

#here we filled categorical data with mode
train_data["Electrical"] = train_data["Electrical"].fillna(train_data["Electrical"].mode()[0])
# here we filled categorical values with None
basmt = ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']
for col in basmt:
    train_data[col] = train_data[col].fillna("None")
#filled the missing values with None
Grg = ['GarageType', 'GarageFinish', 'GarageQual', 'GarageCond']
for col in Grg:
    train_data[col] = train_data[col].fillna("None")

#columns haveing missing values replaces with None as well
train_data["FireplaceQu"] = train_data["FireplaceQu"].fillna("None")
train_data["Fence"] = train_data["Fence"].fillna("None")
train_data["Alley"] = train_data["Alley"].fillna("None")

#special case
train_data['MasVnrType'].fillna('None', inplace=True)

#check if any missing values remain
print(train_data.isnull().sum().sort_values(ascending=False).head(10))

PoolQC          1453
MiscFeature     1406
HalfBath           0
GarageType         0
FireplaceQu        0
Fireplaces         0
Functional         0
TotRmsAbvGrd       0
KitchenQual        0
KitchenAbvGr       0
dtype: int64

C:\Users\M.Aheed Siddiqui\AppData\Local\Temp\ipykernel_20472\4089799352.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_data['MasVnrType'].fillna('None', inplace=True)

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:

# Select categorical columns
categorical_cols = ["CentralAir"]

# Initialize encoder
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit and transform
encoded_array = encoder.fit_transform(train_data[categorical_cols])

# Create DataFrame of encoded values
encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(categorical_cols)
)

# Reset index to avoid alignment issues
encoded_df.index = train_data.index

# Drop original categorical columns
train_data = train_data.drop(columns=categorical_cols)

# Concatenate encoded columns
train_data = pd.concat([train_data, encoded_df], axis=1)
train_data.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory,CentralAir_N,CentralAir_Y
0,0,1,60,RL,65.0,8450,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,None,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,None,NaN,0,2,2008,WD,Normal,208500,2,0.0,1.0
1,1,2,20,RL,80.0,9600,Pave,None,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,None,NaN,0,5,2007,WD,Normal,181500,1,0.0,1.0
2,2,3,60,RL,68.0,11250,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,None,NaN,0,9,2008,WD,Normal,223500,2,0.0,1.0
3,3,4,70,RL,60.0,9550,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,None,NaN,0,2,2006,WD,Abnorml,140000,1,0.0,1.0
4,4,5,60,RL,84.0,14260,Pave,None,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,None,NaN,0,12,2008,WD,Normal,250000,2,0.0,1.0

In [14]:
# #values in train data set
# train_cols = train_data.columns
# missing_train_cols = []
# missing_train_value = []
# for col in train_cols:
#     if train_data[col].isnull().any():
#         missing_train_cols.append(col)
#         missing_train_value.append(train_data[col].isnull().sum())
#         print(f"column {col} have {train_data[col].isnull().sum()} missing values")
#         #print(missing_train_cols,missing_train_val)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
lables_encoders = {}
# Redefine categorical_cols to include all remaining object columns in train_data
categorical_cols = train_data.select_dtypes(include='object').columns
for col in categorical_cols:
  le = LabelEncoder()
  train_data[col] = le.fit_transform(train_data[col].astype(str))
  lables_encoders[col] = le

In [17]:
catergorical_col =  train_data.select_dtypes(include = ("object")).columns

In [18]:
catergorical_col

Index([], dtype='object')

In [19]:
train_data.to_csv("house_price_classification_clean_Data.csv")

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
y = train_data['PriceCategory']
X = train_data.drop(["Id","PriceCategory"],axis=1)

In [22]:
X_train1,X_test1,y_train1,y_test1 = train_test_split(X,y,test_size = 0.30, random_state = 42)

In [23]:
X_train2,X_test2,y_train2,y_test2 = train_test_split(X,y,test_size = 0.25, random_state = 42)

In [24]:
X_train3,X_test3,y_train3,y_test3 = train_test_split(X,y,test_size = 0.20, random_state = 42)

In [25]:
X_train_70 = pd.concat((X_train1,y_train1),axis=1)
X_train_75 = pd.concat((X_train2,y_train2),axis=1)
X_train_80 = pd.concat((X_train3,y_train3),axis=1)

In [26]:
X_train_70.head()

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,CentralAir_N,CentralAir_Y,PriceCategory
135,135,20,3,80.0,10400,1,1,3,3,0,4,0,14,2,2,0,2,7,6,1970,1970,3,1,9,10,1,288.0,3,4,2,4,4,3,6,0,6,0,1304,1304,1,2,4,1682,0,0,1682,0,0,2,0,3,1,3,7,6,1,2,1,1970.0,3,2,530,5,5,2,98,0,0,0,0,0,3,2,4,0,5,2008,8,4,174000,0.0,1.0,1
1452,1452,180,4,35.0,3675,1,1,3,3,0,4,0,7,2,2,4,7,5,5,2005,2005,1,1,12,13,1,80.0,3,4,2,2,4,1,2,547,6,0,0,547,1,2,4,1072,0,0,1072,1,0,1,0,2,1,3,5,6,0,3,2,2005.0,0,2,525,5,5,2,0,28,0,0,0,0,3,4,4,0,5,2006,8,4,145000,0.0,1.0,1
762,762,60,1,72.0,8640,1,1,3,3,0,4,0,21,2,2,0,5,7,5,2009,2009,1,1,12,13,2,0.0,3,4,2,2,4,2,2,24,6,0,732,756,1,0,4,764,783,0,1547,0,0,2,1,3,1,2,7,6,0,3,1,2009.0,3,2,614,5,5,2,169,45,0,0,0,0,3,4,4,0,6,2010,2,4,215200,0.0,1.0,2
932,932,20,3,84.0,11670,1,1,0,3,0,0,0,21,8,2,0,2,9,5,2006,2006,3,1,12,7,3,302.0,0,4,2,0,1,3,6,0,6,0,1905,1905,1,0,4,1905,0,0,1905,0,0,2,0,3,1,0,8,6,1,2,1,2006.0,0,3,788,5,5,2,0,191,0,0,0,0,3,4,4,0,3,2007,8,4,320000,0.0,1.0,2
435,435,60,3,43.0,10667,1,1,1,3,0,1,0,5,4,2,0,5,7,6,1996,1996,1,1,12,13,2,0.0,2,4,2,2,4,0,2,385,0,344,70,799,1,0,4,827,834,0,1661,1,0,2,1,3,1,2,6,6,1,5,1,1996.0,2,2,550,5,5,2,158,61,0,0,0,0,3,4,4,0,4,2009,5,4,212000,0.0,1.0,2

In [27]:
X_train_70["PriceCategory"].unique()

array([1, 2, 0])

In [28]:
X_test_70 = pd.concat((X_test1,y_test1),axis=1)
X_test_75 = pd.concat((X_test2,y_test2),axis=1)
X_test_80 = pd.concat((X_test3,y_test3),axis=1)

In [29]:
X_train_70.to_csv("X_train_70.csv")

In [30]:
X_train_75.to_csv("X_train_75.csv")

In [31]:
X_train_80.to_csv("X_train_80.csv")

In [32]:
X_test_70.to_csv("X_test_70.csv")

In [33]:
X_test_75.to_csv("X_test_75.csv")

In [34]:
X_test_80.to_csv("X_test_80.csv")

## Part A: Decision Tree Algorithm

We will train a Decision Tree Classifier on the house price data using four different hyperparameter combinations:

| # | Criterion | max_depth |
|---|-----------|----------|
| 1 | entropy   | 4        |
| 2 | entropy   | 5        |
| 3 | gini      | 4        |
| 4 | gini      | 5        |

Since `SalePrice` is a continuous variable and entropy/gini are classification criteria, we first convert `SalePrice` into price categories (Low, Medium, High) based on percentile ranges. This way we can properly use a classifier here.

In [35]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
import numpy as np

In [36]:
X_train = pd.read_csv("X_train_70.csv")
X_test = pd.read_csv("X_test_70.csv")

In [37]:
X_train.shape

(1022, 84)

### Preparing Features and Target

In [38]:
y_train = X_train["PriceCategory"]
y_test = X_test["PriceCategory"]
x_train  =X_train.drop(["SalePrice","PriceCategory"], axis = 1)
x_test  =X_test.drop(["SalePrice","PriceCategory"], axis = 1)

In [39]:
y_test.unique()

array([1, 2, 0])

In [40]:
from joblib import dump

### Model 1 — Criterion: Entropy, max_depth: 4

In [41]:
def DecTree(x_train, y_train, x_test, y_test, criterion, max_depth,split_size):
  dt1 = DecisionTreeClassifier(criterion=criterion, max_depth=max_depth, random_state=42)
  dt1.fit(x_train, y_train)
  y_pred1 = dt1.predict(x_test)
  filename = f"DT_{criterion}_{max_depth}_{split_size}.joblib"
  dump(dt1,filename)
  return(f'Accuracy: {accuracy_score(y_test, y_pred1):.4f}')
dectree70 = DecTree(x_train, y_train, x_test, y_test,"entropy",4,70)
print(dectree70)

Accuracy: 0.7740

###DECISION TREE WITH ENTROPY MAX DEPTH 4

In [42]:
X_train75 = pd.read_csv("X_train_75.csv")
X_test75 = pd.read_csv("X_test_75.csv")

In [43]:
y_train75 = X_train75["PriceCategory"]
y_test75 = X_test75["PriceCategory"]
x_train75  =X_train75.drop(["SalePrice","PriceCategory"], axis = 1)
x_test75  =X_test75.drop(["SalePrice","PriceCategory"], axis = 1)

In [44]:
dectree75 = DecTree(x_train75, y_train75, x_test75, y_test75,"entropy",4,75)
print(dectree75)

Accuracy: 0.7863

In [45]:
X_train80 = pd.read_csv("X_train_80.csv")
X_test80 = pd.read_csv("X_test_80.csv")

In [46]:
y_train80 = X_train80["PriceCategory"]
y_test80 = X_test80["PriceCategory"]
x_train80  =X_train80.drop(["SalePrice","PriceCategory"], axis = 1)
x_test80  =X_test80.drop(["SalePrice","PriceCategory"], axis = 1)

In [47]:
dectree80 = DecTree(x_train80, y_train80, x_test80, y_test80,"entropy",4,80)
print(dectree80)

Accuracy: 0.7603

######DECISION TREE WITH ENTROPY MAX DEPTH 5

In [48]:
dectree70 = DecTree(x_train, y_train, x_test, y_test,"entropy",5,70)
print(dectree70)

Accuracy: 0.7808

In [49]:
dectree75 = DecTree(x_train75, y_train75, x_test75, y_test75,"entropy",5,75)
print(dectree75)

Accuracy: 0.7808

In [50]:
dectree80 = DecTree(x_train80, y_train80, x_test80, y_test80,"entropy",5,80)
print(dectree80)

Accuracy: 0.7705

######DECISION TREE WITH GINI MAX DEPTH 4

In [51]:
dectree70 = DecTree(x_train, y_train, x_test, y_test,"gini",4,70)
print(dectree70)

Accuracy: 0.7580

In [52]:
dectree75 = DecTree(x_train75, y_train75, x_test75, y_test75,"gini",4,75)
print(dectree75)

Accuracy: 0.7781

In [53]:
dectree80 = DecTree(x_train80, y_train80, x_test80, y_test80,"gini",4,80)
print(dectree80)

Accuracy: 0.7500

###DECISION TREE WITH GINI MAX DEPTH 5

In [54]:
dectree70 = DecTree(x_train, y_train, x_test, y_test,"gini",5,70)
print(dectree70)

Accuracy: 0.7763

In [55]:
dectree75 = DecTree(x_train75, y_train75, x_test75, y_test75,"gini",5,75)
print(dectree75)

Accuracy: 0.7808

In [56]:
dectree80 = DecTree(x_train80, y_train80, x_test80, y_test80,"gini",5,80)
print(dectree80)

Accuracy: 0.8048

In [57]:
from sklearn.model_selection import GridSearchCV

param_grid = {
   "criterion" : ["gini","entropy"],
   "max_depth" : [4,5]
}
dt = DecisionTreeClassifier(random_state = 42)
grid_search = GridSearchCV(dt,param_grid,cv=10, scoring = "accuracy")

grid_search.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'], 'max_depth': [4, 5]},
             scoring='accuracy')

In [58]:
print("All combinations tried:")
cv_results = pd.DataFrame(grid_search.cv_results_)[['param_criterion', 'param_max_depth', 'mean_test_score']]
cv_results.columns = ['Criterion', 'max_depth', 'Avg CV Accuracy']
print(cv_results.to_string(index=False))

print(f"\nBest Parameters: {grid_search.best_params_}")
print(f"Best CV Accuracy: {grid_search.best_score_:.4f}")
print(f"Test Accuracy: {grid_search.score(x_test, y_test):.4f}")

All combinations tried:
Criterion  max_depth  Avg CV Accuracy
     gini          4         0.739758
     gini          5         0.746602
  entropy          4         0.730954
  entropy          5         0.739749

Best Parameters: {'criterion': 'gini', 'max_depth': 5}
Best CV Accuracy: 0.7466
Test Accuracy: 0.7763