# Encoding

In [138]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [110]:
df = pd.read_csv('emp.csv')

In [111]:
df.head()

   empno   ename        job     mgr    hiredate   sal    comm  deptno
0   7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10
1   7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30
2   7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10
3   7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20
4   7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30

In [112]:
df.shape

(14, 8)

In [113]:
df2 = df.copy()

In [114]:
sorted(df2["job"].unique())

['ANALYST', 'CLERK', 'MANAGER', 'PRESIDENT', 'SALESMAN']

In [115]:
df2["job"].value_counts()

job
SALESMAN     4
CLERK        4
MANAGER      3
ANALYST      2
PRESIDENT    1
Name: count, dtype: int64

In [116]:
cols_name = {"job" : {"ANALYST" : 3, "CLERK" : 5, "MANAGER" : 2, "PRESIDENT" : 1, "SALESMAN" : 4}}

In [117]:
cols_name

{'job': {'ANALYST': 3,
  'CLERK': 5,
  'MANAGER': 2,
  'PRESIDENT': 1,
  'SALESMAN': 4}}

In [118]:
df2 = df2.replace(cols_name)
df2.head()

/tmp/ipykernel_23298/1622986362.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2 = df2.replace(cols_name)

   empno   ename  job     mgr    hiredate   sal    comm  deptno
0   7839    KING    1     NaN  11/17/2001  5000     NaN      10
1   7698   BLAKE    2  7839.0  05/01/2001  2850     NaN      30
2   7782   CLARK    2  7839.0  06/09/2001  2450     NaN      10
3   7566   JONES    2  7839.0  04/02/2001  2975     NaN      20
4   7654  MARTIN    4  7698.0  09/28/2001  1250  1400.0      30

In [119]:
def salCatg(salary):
  if salary >= 3000:
    r=1
  elif salary >= 1500:
    r=2
  else:
    r=3
  return r

In [120]:
df2["sal"] = df2["sal"].apply(salCatg)
df2.head()

   empno   ename  job     mgr    hiredate  sal    comm  deptno
0   7839    KING    1     NaN  11/17/2001    1     NaN      10
1   7698   BLAKE    2  7839.0  05/01/2001    2     NaN      30
2   7782   CLARK    2  7839.0  06/09/2001    2     NaN      10
3   7566   JONES    2  7839.0  04/02/2001    2     NaN      20
4   7654  MARTIN    4  7698.0  09/28/2001    3  1400.0      30

In [121]:
df3 = df.copy()
df.dtypes

empno         int64
ename        object
job          object
mgr         float64
hiredate     object
sal           int64
comm        float64
deptno        int64
dtype: object

In [122]:
df3["job"] = df3["job"].astype("category")
df3.dtypes

empno          int64
ename         object
job         category
mgr          float64
hiredate      object
sal            int64
comm         float64
deptno         int64
dtype: object

In [123]:
sorted(df3["job"].unique())

['ANALYST', 'CLERK', 'MANAGER', 'PRESIDENT', 'SALESMAN']

In [124]:
df3["job1"] = df3["job"].cat.codes

In [125]:
df3.head()

   empno   ename        job     mgr    hiredate   sal    comm  deptno  job1
0   7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10     3
1   7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30     2
2   7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10     2
3   7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20     2
4   7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30     4

In [126]:
df3["comm"] = df3["comm"].astype("category")

In [127]:
sorted(df3["comm"].unique())

[nan, 0.0, 300.0, 500.0, 1400.0]

In [128]:
df3["comm1"] = df3["comm"].cat.codes

In [129]:
df3.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,job1,comm1
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,3,-1
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,2,-1
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,2,-1
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,2,-1
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,4,3

# One Hot Encoding (Dummies)

In [130]:
df4 = df.copy()

In [131]:
sorted(df4["deptno"].unique())

[np.int64(10), np.int64(20), np.int64(30)]

In [132]:
df4["depID"] = df4["deptno"]
df4.head()

   empno   ename        job     mgr    hiredate   sal    comm  deptno  depID
0   7839    KING  PRESIDENT     NaN  11/17/2001  5000     NaN      10     10
1   7698   BLAKE    MANAGER  7839.0  05/01/2001  2850     NaN      30     30
2   7782   CLARK    MANAGER  7839.0  06/09/2001  2450     NaN      10     10
3   7566   JONES    MANAGER  7839.0  04/02/2001  2975     NaN      20     20
4   7654  MARTIN   SALESMAN  7698.0  09/28/2001  1250  1400.0      30     30

In [133]:
pd.get_dummies(df4, columns=["deptno"], prefix=["dno"]).head()

,empno,ename,job,mgr,hiredate,sal,comm,depID,dno_10,dno_20,dno_30
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,True,False,False
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,False,False,True
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,True,False,False
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,False,True,False
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,False,False,True

# Custom Binary Encoding (Target Encoding)

In [134]:
df3["CBE code"] = np.where(df3["hiredate"].str.contains("2001"), 1, 0)

In [135]:
df3.head()

,empno,ename,job,mgr,hiredate,sal,comm,deptno,job1,comm1,CBE code
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,3,-1,1
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,2,-1,1
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,2,-1,1
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,2,-1,1
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,4,3,1

In [136]:
df3[["ename", "hiredate", "CBE code"]].head(14)

     ename    hiredate  CBE code
0     KING  11/17/2001         1
1    BLAKE  05/01/2001         1
2    CLARK  06/09/2001         1
3    JONES  04/02/2001         1
4   MARTIN  09/28/2001         1
5    ALLEN  02/20/2001         1
6   TURNER  09/08/2001         1
7    JAMES  12/03/2001         1
8     WARD  02/22/2001         1
9     FORD  02/03/2001         1
10   SMITH  12/17/2000         0
11   SCOTT  04/19/2007         0
12   ADAMS  05/23/2007         0
13  MILLER  01/23/2002         0

In [137]:
df3[df3["CBE code"] == 1]

,empno,ename,job,mgr,hiredate,sal,comm,deptno,job1,comm1,CBE code
0,7839,KING,PRESIDENT,NaN,11/17/2001,5000,NaN,10,3,-1,1
1,7698,BLAKE,MANAGER,7839.0,05/01/2001,2850,NaN,30,2,-1,1
2,7782,CLARK,MANAGER,7839.0,06/09/2001,2450,NaN,10,2,-1,1
3,7566,JONES,MANAGER,7839.0,04/02/2001,2975,NaN,20,2,-1,1
4,7654,MARTIN,SALESMAN,7698.0,09/28/2001,1250,1400.0,30,4,3,1
5,7499,ALLEN,SALESMAN,7698.0,02/20/2001,1600,300.0,30,4,1,1
6,7844,TURNER,SALESMAN,7698.0,09/08/2001,1500,0.0,30,4,0,1
7,7900,JAMES,CLERK,7698.0,12/03/2001,950,NaN,30,1,-1,1
8,7521,WARD,SALESMAN,7698.0,02/22/2001,1250,500.0,30,4,2,1
9,7902,FORD,ANALYST,7566.0,02/03/2001,3000,NaN,20,0,-1,1

# Ordinal Encoding

In [139]:
sorted(df3["deptno"].unique())

[np.int64(10), np.int64(20), np.int64(30)]

In [141]:
ord_enc = OrdinalEncoder()
df3["dno_code"] = ord_enc.fit_transform(df3[["deptno"]])
df3[["ename", "deptno", "dno_code"]].head(14)

     ename  deptno  dno_code
0     KING      10       0.0
1    BLAKE      30       2.0
2    CLARK      10       0.0
3    JONES      20       1.0
4   MARTIN      30       2.0
5    ALLEN      30       2.0
6   TURNER      30       2.0
7    JAMES      30       2.0
8     WARD      30       2.0
9     FORD      20       1.0
10   SMITH      20       1.0
11   SCOTT      20       1.0
12   ADAMS      20       1.0
13  MILLER      10       0.0