In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [ ]:
train_data = pd.read_csv('house_price_classification.csv')
train_data.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,2
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,1
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,...,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,2
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,1
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,...,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,2

In [ ]:
train_data.shape

(1460, 83)

In [ ]:
train_data

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,2
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,1
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,...,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,2
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,1
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,...,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,...,NaN,NaN,NaN,0,8,2007,WD,Normal,175000,1
1456,1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,...,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000,2
1457,1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,...,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500,2
1458,1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,...,NaN,NaN,NaN,0,4,2010,WD,Normal,142125,1
1459,1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,...,NaN,NaN,NaN,0,6,2008,WD,Normal,147500,1

In [ ]:
train_cols =  train_data.columns
missing_train_cols = []
missing_train_vals = []
for col in train_cols:
  if train_data[col].isnull().sum() > 0:
    missing_train_cols.append(col)
    missing_train_vals.append(train_data[col].isnull().sum())
    print(f"column {col} have {train_data[col].isnull().sum()} missing values.")

column LotFrontage have 259 missing values.
column Alley have 1369 missing values.
column MasVnrType have 872 missing values.
column MasVnrArea have 8 missing values.
column BsmtQual have 37 missing values.
column BsmtCond have 37 missing values.
column BsmtExposure have 38 missing values.
column BsmtFinType1 have 37 missing values.
column BsmtFinType2 have 38 missing values.
column Electrical have 1 missing values.
column FireplaceQu have 690 missing values.
column GarageType have 81 missing values.
column GarageYrBlt have 81 missing values.
column GarageFinish have 81 missing values.
column GarageQual have 81 missing values.
column GarageCond have 81 missing values.
column PoolQC have 1453 missing values.
column Fence have 1179 missing values.
column MiscFeature have 1406 missing values.

In [ ]:
a = ["LotFrontage", "MasVnrArea", "GarageYrBlt"]
for i in a:
  train_data[i].fillna(train_data[i].median(), inplace=True)

In [ ]:
train_data["Electrical"].fillna(train_data["Electrical"].mode()[0], inplace=True)

In [ ]:
bsmt_cols = ["BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2"]
for i in bsmt_cols:
  train_data[i].fillna("None", inplace=True)

In [ ]:
garage_cols = ["GarageType", "GarageFinish", "GarageQual", "GarageCond"]
for i in garage_cols:
  train_data[i].fillna("None", inplace=True)

In [ ]:
high_missing_cols = ["Alley", "FireplaceQu", "Fence", "PoolQC", "MiscFeature"]
for col in high_missing_cols:
  train_data[col].fillna("None", inplace=True)

In [ ]:
train_data["MasVnrType"].fillna("None", inplace=True)

In [ ]:
train_data.isnull().sum().sum()

np.int64(0)

In [ ]:
categorical_cols = train_data.select_dtypes(include='object').columns

In [ ]:
categorical_cols = categorical_cols.tolist()
categorical_cols = categorical_cols.remove("SaleCondition")

In [ ]:
one_SaleCondition = ["SaleCondition"]

In [ ]:
ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded_data = ohe.fit_transform(train_data[one_SaleCondition])
encoded_df = pd.DataFrame(encoded_data, columns=ohe.get_feature_names_out(one_SaleCondition))
train_data = train_data.reset_index(drop=True)
train_data = pd.concat([train_data, encoded_df], axis=1)
train_data.drop(one_SaleCondition, axis=1, inplace=True)

In [ ]:
label_encoders = {}

categorical_cols = train_data.select_dtypes(include='object').columns.tolist()

for col in categorical_cols:
  le = LabelEncoder()
  train_data[col] = le.fit_transform(train_data[col].astype("str"))
  label_encoders[col] = le

In [ ]:
train_data.to_csv("/content/house_price_classification_cleaned.csv", index=False)