# 6 - Review Analysis System

In [1]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download("vader_lexicon")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download('punkt_tab')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [2]:
df = pd.read_csv('amazon.csv')

In [3]:
df.head()

                                          reviewText  Positive
0  This is a one of the best apps acording to a b...         1
1  This is a pretty good version of the game for ...         1
2  this is a really cool game. there are a bunch ...         1
3  This is a silly game and can be frustrating, b...         1
4  This is a terrific game on any pad. Hrs of fun...         1

In [4]:
df.shape

(20000, 2)

In [5]:
analyzer = SentimentIntensityAnalyzer()

In [6]:
def get_sentiment(text):
  scores = analyzer.polarity_scores(text)
  sentiment = 1 if scores["pos"] > 0 else 0
  return sentiment

In [7]:
df["sentiment"] = df["reviewText"].apply(get_sentiment)

In [8]:
df.head()

                                          reviewText  Positive  sentiment
0  This is a one of the best apps acording to a b...         1          1
1  This is a pretty good version of the game for ...         1          1
2  this is a really cool game. there are a bunch ...         1          1
3  This is a silly game and can be frustrating, b...         1          1
4  This is a terrific game on any pad. Hrs of fun...         1          1

In [9]:
scores = analyzer.polarity_scores("one best apps acording bunch people agree bomb")
print(f"Positive: {scores['pos']*100:.2f}%")
print(f"Negative: {scores['neg']*100:.2f}%")
print(f"Neutral: {scores['neu']*100:.2f}%")

Positive: 45.00%
Negative: 21.50%
Neutral: 33.60%

 # 7 - The Simple Perceptron

In [10]:
import numpy as np

class Perceptron:
    def __init__(self, num_features, learning_rate=0.01):
        self.weights = np.zeros(num_features)
        self.bias = 0
        self.learning_rate = learning_rate

    def weighted_sum(self, inputs):
        return np.dot(inputs, self.weights) + self.bias

    def activate(self, weighted_sum):
        return 1 if weighted_sum >= 0 else 0

    def predict(self, inputs):
        return self.activate(self.weighted_sum(inputs))

    def train(self, X, y, epochs=10):
        for _ in range(epochs):
            for inputs, label in zip(X, y):
                prediction = self.predict(inputs)
                error = label - prediction
                self.weights += self.learning_rate * error * inputs
                self.bias += self.learning_rate * error
        print("Training complete.")

This **Perceptron** class can be used to create a simple linear classifier. Let's create a dummy dataset to demonstrate its usage.

In [11]:
X_dummy = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y_dummy = np.array([0, 0, 0, 1])

perceptron = Perceptron(num_features=2, learning_rate=0.1)
perceptron.train(X_dummy, y_dummy, epochs=10)

print("\nPredictions after training:")
for inputs, label in zip(X_dummy, y_dummy):
    prediction = perceptron.predict(inputs)
    print(f"Input: {inputs}, Actual: {label}, Predicted: {prediction}")

print(f"\nFinal Weights: {perceptron.weights}")
print(f"Final Bias: {perceptron.bias}")

Training complete.

Predictions after training:
Input: [0 0], Actual: 0, Predicted: 0
Input: [0 1], Actual: 0, Predicted: 0
Input: [1 0], Actual: 0, Predicted: 0
Input: [1 1], Actual: 1, Predicted: 1

Final Weights: [0.2 0.1]
Final Bias: -0.20000000000000004

# 8 - Named Entity Recognition

In [12]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag
from nltk.chunk import ne_chunk
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package maxent_ne_chunker is already up-to-date!
[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

In [13]:
sample_news_text = """President Joe Biden met with German Chancellor Olaf Scholz in Washington D.C. today to discuss global security issues. They addressed concerns about the conflict in Ukraine and the economic impact on Europe. The meeting took place at the White House. Google's CEO Sundar Pichai also attended a technology summit in California."""

In [ ]:
words = word_tokenize(sample_news_text)
pos_tags = pos_tag(words)
named_entities = ne_chunk(pos_tags)
entities = {}
for chunk in named_entities:
  if hasattr(chunk, 'label'):
    entity_type = chunk.label()
    entity_name = ' '.join([c[0] for c in chunk])
    if entity_type not in entities:
        entities[entity_type] = []
    entities[entity_type].append(entity_name)
print("Grouped Named Entities:")
for entity_type, names in entities.items():
    print(f"{entity_type}: {', '.join(set(names))}")

# 9 - Classification Prediction Logic

In [15]:
import numpy as np

target_X = np.array([1.0, 0.1, 1.0, 0.1, 1.0, 0.1, 1.0, 0.1, 1.0, 0.1, 1.0, 0.1])
target_O = np.array([0.1, 1.0, 0.1, 1.0, 0.1, 1.0, 0.1, 1.0, 0.1, 1.0, 0.1, 1.0])

print("Target vector for 'X':", target_X)
print("Target vector for 'O':", target_O)

Target vector for 'X': [1.  0.1 1.  0.1 1.  0.1 1.  0.1 1.  0.1 1.  0.1]
Target vector for 'O': [0.1 1.  0.1 1.  0.1 1.  0.1 1.  0.1 1.  0.1 1. ]

In [16]:
def predict_class(input_vector, target_X, target_O):
  dist_to_X = np.linalg.norm(input_vector - target_X)
  dist_to_O = np.linalg.norm(input_vector - target_O)
  similarity_X = -dist_to_X
  similarity_O = -dist_to_O

  exp_sim_X = np.exp(similarity_X)
  exp_sim_O = np.exp(similarity_O)

  total_exp_sim = exp_sim_X + exp_sim_O

  prob_X = exp_sim_X / total_exp_sim
  prob_O = exp_sim_O / total_exp_sim

  if prob_X > prob_O:
      predicted_class = 'X'
      probability = prob_X
  else:
      predicted_class = 'O'
      probability = prob_O

  return predicted_class, probability, {'X': prob_X, 'O': prob_O}

In [20]:
input_vector_X_like = np.array([1.1, 0.0, 0.9, 0.2, 1.1, 0.0, 0.9, 0.2, 1.1, 0.0, 0.9, 0.2])
predicted_class_X, prob_X_like, all_probs_X = predict_class(input_vector_X_like, target_X, target_O)
print(f"Input vector (X-like): {input_vector_X_like}")
print(f"Predicted Class: {predicted_class_X}, Probability: {prob_X_like:.4f}")
print(f"Full Probabilities: {all_probs_X}")

Input vector (X-like): [1.1 0.  0.9 0.2 1.1 0.  0.9 0.2 1.1 0.  0.9 0.2]
Predicted Class: X, Probability: 0.9422
Full Probabilities: {'X': np.float64(0.9421585140837065), 'O': np.float64(0.05784148591629347)}

In [21]:
input_vector_O_like = np.array([0.0, 1.1, 0.2, 0.9, 0.0, 1.1, 0.2, 0.9, 0.0, 1.1, 0.2, 0.9])
predicted_class_O, prob_O_like, all_probs_O = predict_class(input_vector_O_like, target_X, target_O)
print(f"\nInput vector (O-like): {input_vector_O_like}")
print(f"Predicted Class: {predicted_class_O}, Probability: {prob_O_like:.4f}")
print(f"Full Probabilities: {all_probs_O}")

Input vector (O-like): [0.  1.1 0.2 0.9 0.  1.1 0.2 0.9 0.  1.1 0.2 0.9]
Predicted Class: O, Probability: 0.9422
Full Probabilities: {'X': np.float64(0.05784148591629347), 'O': np.float64(0.9421585140837065)}

In [22]:
input_vector_ambiguous = np.array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5])
predicted_class_ambiguous, prob_ambiguous, all_probs_ambiguous = predict_class(input_vector_ambiguous, target_X, target_O)
print(f"\nInput vector (Ambiguous): {input_vector_ambiguous}")
print(f"Predicted Class: {predicted_class_ambiguous}, Probability: {prob_ambiguous:.4f}")
print(f"Full Probabilities: {all_probs_ambiguous}")

Input vector (Ambiguous): [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
Predicted Class: O, Probability: 0.5000
Full Probabilities: {'X': np.float64(0.5), 'O': np.float64(0.5)}

## Conclusion

This notebook demonstrated several Natural Language Processing (NLP) and machine learning techniques, including:

*   **Sentiment Analysis:** Using NLTK's VADER for sentiment scoring on Amazon reviews.
*   **Simple Perceptron:** Implementation and training of a basic perceptron model.
*   **Named Entity Recognition (NER):** Extracting entities like persons, organizations, and locations from text using NLTK.
*   **Classification Prediction Logic:** A custom classification method based on Euclidean distance and softmax probabilities.

Each section provided foundational concepts and practical code examples for understanding these core areas in AI and data science.