In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# preprocessed data
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop('species', axis = 1)
y = df['species']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
# if model gets accuracy of 100% its overfit
model_knn = KNeighborsClassifier(n_neighbors = 13)

In [10]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.score(X_test, y_test)

1.0

In [12]:
from sklearn.svm import SVC

In [13]:
# model_svm = SVC(C = 10, kernel = 'linear', gamma = 'auto')
model_svm = SVC(gamma = 'auto')

In [14]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [15]:
model_svm.score(X_test, y_test)

1.0

# Now lets use the GRID Search CV

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
# GRID CV ON SVM

In [18]:
classifier = GridSearchCV((model_svm), {
    'C' : [1, 10, 20, 30],
    'kernel' : ['rbf', 'linear'],
}, cv = 5, return_train_score = False)

In [19]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [20]:
classifier.cv_results_

{'mean_fit_time': array([0.00440059, 0.00382657, 0.0044991 , 0.00386329, 0.00434279,
        0.00402427, 0.00386057, 0.00427046]),
 'std_fit_time': array([0.00076305, 0.00023337, 0.00088606, 0.0004931 , 0.0006234 ,
        0.0004279 , 0.00029947, 0.00064549]),
 'mean_score_time': array([0.00310087, 0.00291266, 0.00302005, 0.00290446, 0.00357146,
        0.00283294, 0.00288258, 0.00297122]),
 'std_score_time': array([0.00040724, 0.00019465, 0.00022953, 0.00034942, 0.00038537,
        0.00015182, 0.00020301, 0.0002356 ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [21]:
results = pd.DataFrame(classifier.cv_results_)

In [22]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004401,0.000763,0.003101,0.000407,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003827,0.000233,0.002913,0.000195,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004499,0.000886,0.003020,0.000230,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.003863,0.000493,0.002904,0.000349,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.004343,0.000623,0.003571,0.000385,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.004024,0.000428,0.002833,0.000152,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003861,0.000299,0.002883,0.000203,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.004270,0.000645,0.002971,0.000236,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [23]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [24]:
### GRID CV ON KNN

In [25]:
classifier_knn = GridSearchCV((model_knn), {
    'n_neighbors' : [1, 5, 10, 15],
    'weights' : ['uniform', 'distance'],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute']
}, cv = 5, return_train_score = False)

In [26]:
classifier_knn.fit(X, y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 5, 10, 15],
                         'weights': ['uniform', 'distance']})

In [27]:
classifier_knn.cv_results_

{'mean_fit_time': array([0.00409012, 0.00508327, 0.00387249, 0.00327306, 0.00466599,
        0.00326486, 0.00441728, 0.0035944 , 0.00352139, 0.00362124,
        0.00303035, 0.00358505, 0.00529141, 0.00318956, 0.00288916,
        0.00303559, 0.00390735, 0.00301375, 0.00318885, 0.00376668,
        0.00352397, 0.00386491, 0.00382986, 0.00351253, 0.00355983,
        0.00383883, 0.00353317, 0.00355997, 0.00321932, 0.00337138,
        0.00312958, 0.00346198]),
 'std_fit_time': array([6.28896177e-04, 2.89367003e-03, 2.84446878e-04, 2.17006354e-04,
        1.45182820e-03, 2.66332502e-04, 1.60923247e-03, 3.28879569e-04,
        3.07137413e-04, 7.40310329e-04, 4.78630352e-04, 6.38306114e-04,
        2.87284474e-03, 3.04802502e-04, 8.94389413e-05, 3.88272292e-04,
        1.08657301e-03, 4.22734673e-04, 2.87417647e-04, 7.73654757e-04,
        6.66656353e-04, 1.16324285e-04, 7.25445854e-04, 6.02848411e-04,
        3.10136405e-04, 9.26186056e-04, 4.63519208e-04, 4.29136689e-04,
        2.61743009e-04, 6.33857046e-04, 3.00999792e-04, 3.01511665e-04]),
 'mean_score_time': array([0.00715795, 0.00395646, 0.00589781, 0.00458498, 0.00631456,
        0.00448098, 0.00669837, 0.00471082, 0.00462422, 0.00361986,
        0.00478282, 0.0040864 , 0.00579772, 0.00369654, 0.00495987,
        0.00404449, 0.00620151, 0.00369644, 0.00453401, 0.00414963,
        0.00524774, 0.00523572, 0.00572863, 0.00446844, 0.37549314,
        0.01421738, 0.01214108, 0.01389551, 0.01360154, 0.01575294,
        0.0184967 , 0.02113581]),
 'std_score_time': array([1.87138139e-03, 4.25618944e-04, 5.11997099e-04, 1.20724261e-03,
        3.88007596e-04, 1.98965217e-04, 1.37876649e-03, 5.23556204e-04,
        3.34118766e-04, 2.44714641e-04, 8.84987601e-04, 9.34292789e-04,
        1.08686233e-03, 2.13478116e-04, 3.44408339e-04, 6.34788388e-04,
        2.32216950e-03, 4.72786531e-04, 5.19759917e-04, 5.04901506e-04,
        4.75296837e-04, 6.00433085e-04, 9.03168381e-04, 8.81817768e-04,
        7.24665959e-01, 1.73988630e-03, 2.49407719e-03, 2.23026490e-03,
        1.77995453e-03, 2.54346984e-03, 1.42733874e-02, 1.34587036e-02]),
 'param_algorithm': masked_array(data=['auto', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto',
                    'auto', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[1, 1, 5, 5, 10, 10, 15, 15, 1, 1, 5, 5, 10, 10, 15, 15,
                    1, 1, 5, 5, 10, 10, 15, 15, 1, 1, 5, 5, 10, 10, 15, 15],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'algorithm': 'auto', 'n_neighbors': 1, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 1, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 10, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 10, 'weights': 'distance'},
  {'algorithm': 'auto', 'n_neighbors': 15, 'weights': 'uniform'},
  {'algorithm': 'auto', 'n_neighbors': 15, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 10, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 10, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 15, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 15, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 1, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 1, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 5, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 10, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 10, 'weights': 'distance'},
  {'algorithm': 'brute', 'n_neighbors': 15, 'weights': 'uniform'},
  {'algorithm': 'brute', 'n_neighbors': 15, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 0.96666667, 0.96666667,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 0.96666667, 0.96666667, 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 0.96666667,
        0.96666667, 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.9       , 1.        ,
        1.        , 0.93333333, 0.93333333, 0.93333333, 0.93333333,
        0.93333333, 0.9       , 1.        , 1.        , 0.93333333,
        0.93333333, 0.93333333, 0.93333333, 0.93333333, 0.9       ,
        1.        , 1.        , 0.93333333, 0.93333333, 0.93333333,
        0.93333333, 0.93333333, 0.9       , 1.        , 1.        ,
        0.93333333, 0.93333333]),
 'split3_test_score': array([0.93333333, 0.93333333, 0.96666667, 0.96666667, 0.93333333,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.93333333,
        0.96666667, 0.96666667, 0.93333333, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.93333333, 0.96666667, 0.96666667,
        0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.93333333,
        0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96      , 0.96      , 0.97333333, 0.96666667, 0.98      ,
        0.98666667, 0.96666667, 0.97333333, 0.96      , 0.96      ,
        0.97333333, 0.96666667, 0.98      , 0.98666667, 0.96666667,
        0.97333333, 0.96      , 0.96      , 0.97333333, 0.96666667,
        0.98      , 0.98666667, 0.96666667, 0.97333333, 0.96      ,
        0.96      , 0.97333333, 0.96666667, 0.98666667, 0.98666667,
        0.96666667, 0.97333333]),
 'std_test_score': array([0.02494438, 0.02494438, 0.02494438, 0.03651484, 0.02666667,
        0.01632993, 0.02981424, 0.02494438, 0.02494438, 0.02494438,
        0.02494438, 0.03651484, 0.02666667, 0.01632993, 0.02981424,
        0.02494438, 0.02494438, 0.02494438, 0.02494438, 0.03651484,
        0.02666667, 0.01632993, 0.02981424, 0.02494438, 0.02494438,
        0.02494438, 0.02494438, 0.03651484, 0.01632993, 0.01632993,
        0.02981424, 0.02494438]),
 'rank_test_score': array([25, 25,  9, 17,  6,  1, 17,  9, 25, 25,  9, 17,  6,  1, 17,  9, 25,
        25,  9, 17,  6,  1, 17,  9, 25, 25,  9, 17,  1,  1, 17,  9],
       dtype=int32)}

In [28]:
results_knn = pd.DataFrame(classifier_knn.cv_results_)

In [29]:
results_knn

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004090,0.000629,0.007158,0.001871,auto,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,25
1,0.005083,0.002894,0.003956,0.000426,auto,1,distance,"{'algorithm': 'auto', 'n_neighbors': 1, 'weigh...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,25
2,0.003872,0.000284,0.005898,0.000512,auto,5,uniform,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
3,0.003273,0.000217,0.004585,0.001207,auto,5,distance,"{'algorithm': 'auto', 'n_neighbors': 5, 'weigh...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,17
4,0.004666,0.001452,0.006315,0.000388,auto,10,uniform,"{'algorithm': 'auto', 'n_neighbors': 10, 'weig...",0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,6
5,0.003265,0.000266,0.004481,0.000199,auto,10,distance,"{'algorithm': 'auto', 'n_neighbors': 10, 'weig...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
6,0.004417,0.001609,0.006698,0.001379,auto,15,uniform,"{'algorithm': 'auto', 'n_neighbors': 15, 'weig...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,17
7,0.003594,0.000329,0.004711,0.000524,auto,15,distance,"{'algorithm': 'auto', 'n_neighbors': 15, 'weig...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
8,0.003521,0.000307,0.004624,0.000334,ball_tree,1,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,25
9,0.003621,0.000740,0.003620,0.000245,ball_tree,1,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,25
10,0.003030,0.000479,0.004783,0.000885,ball_tree,5,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
11,0.003585,0.000638,0.004086,0.000934,ball_tree,5,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 5, '...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,17
12,0.005291,0.002873,0.005798,0.001087,ball_tree,10,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 10, ...",0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,6
13,0.003190,0.000305,0.003697,0.000213,ball_tree,10,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 10, ...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
14,0.002889,0.000089,0.004960,0.000344,ball_tree,15,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 15, ...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,17
15,0.003036,0.000388,0.004044,0.000635,ball_tree,15,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 15, ...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
16,0.003907,0.001087,0.006202,0.002322,kd_tree,1,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 1, 'we...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,25
17,0.003014,0.000423,0.003696,0.000473,kd_tree,1,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 1, 'we...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,25
18,0.003189,0.000287,0.004534,0.000520,kd_tree,5,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
19,0.003767,0.000774,0.004150,0.000505,kd_tree,5,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 5, 'we...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,17
20,0.003524,0.000667,0.005248,0.000475,kd_tree,10,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 10, 'w...",0.966667,1.000000,1.000000,0.933333,1.0,0.980000,0.026667,6
21,0.003865,0.000116,0.005236,0.000600,kd_tree,10,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 10, 'w...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
22,0.003830,0.000725,0.005729,0.000903,kd_tree,15,uniform,"{'algorithm': 'kd_tree', 'n_neighbors': 15, 'w...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,17
23,0.003513,0.000603,0.004468,0.000882,kd_tree,15,distance,"{'algorithm': 'kd_tree', 'n_neighbors': 15, 'w...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
24,0.003560,0.000310,0.375493,0.724666,brute,1,uniform,"{'algorithm': 'brute', 'n_neighbors': 1, 'weig...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,25
25,0.003839,0.000926,0.014217,0.001740,brute,1,distance,"{'algorithm': 'brute', 'n_neighbors': 1, 'weig...",0.966667,0.966667,0.933333,0.933333,1.0,0.960000,0.024944,25
26,0.003533,0.000464,0.012141,0.002494,brute,5,uniform,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9
27,0.003560,0.000429,0.013896,0.002230,brute,5,distance,"{'algorithm': 'brute', 'n_neighbors': 5, 'weig...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,17
28,0.003219,0.000262,0.013602,0.001780,brute,10,uniform,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
29,0.003371,0.000634,0.015753,0.002543,brute,10,distance,"{'algorithm': 'brute', 'n_neighbors': 10, 'wei...",0.966667,1.000000,1.000000,0.966667,1.0,0.986667,0.016330,1
30,0.003130,0.000301,0.018497,0.014273,brute,15,uniform,"{'algorithm': 'brute', 'n_neighbors': 15, 'wei...",0.933333,1.000000,0.933333,0.966667,1.0,0.966667,0.029814,17
31,0.003462,0.000302,0.021136,0.013459,brute,15,distance,"{'algorithm': 'brute', 'n_neighbors': 15, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,9

In [30]:
results_knn[['param_n_neighbors', 'param_weights', 'mean_test_score']].head()

   param_n_neighbors param_weights  mean_test_score
0                  1       uniform         0.960000
1                  1      distance         0.960000
2                  5       uniform         0.973333
3                  5      distance         0.966667
4                 10       uniform         0.980000

In [31]:
from sklearn.model_selection import RandomizedSearchCV

In [32]:
classifier_r = RandomizedSearchCV((model_svm), {
    'C' : [1, 10, 20, 30],
    'kernel' : ['rbf', 'linear'],
},n_iter = 4, cv = 5, return_train_score = False)

In [33]:
classifier_r.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [34]:
results = pd.DataFrame(classifier_r.cv_results_)

In [35]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005665,0.000362,0.004515,0.000146,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003532,0.000152,0.002743,0.000258,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3
2,0.004236,0.000529,0.002955,0.000272,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,4
3,0.005296,0.000861,0.005334,0.003732,rbf,20,"{'kernel': 'rbf', 'C': 20}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,2

In [36]:
# here it wasnt needed but use where thousands of parameters

results[['param_kernel', 'param_C', 'mean_test_score']]

# best perform 0	rbf	10	0.980000

  param_kernel  param_C  mean_test_score
0       linear        1         0.980000
1       linear       20         0.966667
2          rbf       30         0.960000
3          rbf       20         0.966667